---

- name: "SECTION | 18.1 | Control Panel"
  ansible.builtin.import_tasks:
      file: section_18.1/main.yml

- name: "SECTION | 18.4 | MS Security Guide"
  ansible.builtin.import_tasks:
      file: section_18.4/main.yml

- name: "SECTION | 18.5 | MSS (Legacy)"
  ansible.builtin.import_tasks:
      file: section_18.5/main.yml

- name: "SECTION | 18.6 | Network"
  ansible.builtin.import_tasks:
      file: section_18.6/main.yml

- name: "SECTION | 18.7 | Printers"
  ansible.builtin.import_tasks:
      file: section_18.7/main.yml

- name: "SECTION | 18.8 | Start Menu & Task Bar"
  ansible.builtin.import_tasks:
      file: section_18.8/main.yml

- name: "SECTION | 18.9 | System"
  ansible.builtin.import_tasks:
      file: section_18.9/main.yml

- name: "SECTION | 18.10 | Windows Components"
  ansible.builtin.import_tasks:
      file: section_18.10/main.yml
