---

- name: Display Banner
  ansible.builtin.debug:
      msg: "{{ lockdown_banner.split('\n') }}"
  tags:
      - always

- name: Gather distribution info
  ansible.builtin.setup:
      gather_subset: distribution,!all,!min
  when:
      - ansible_distribution is not defined
  tags:
      - always

- name: Check OS Version & Family
  ansible.builtin.assert:
      that:
          - ansible_os_family == 'Windows'
          - ansible_distribution | regex_search('(Microsoft Windows 10 Enterprise)')
      success_msg: "{{ ansible_distribution }} Distribution {{ ansible_distribution_major_version }} is the detected operating system."
      fail_msg: "This role can only be run against Microsoft Windows 10 Enterprise. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  tags:
      - always

- name: Check Ansible Version
  ansible.builtin.assert:
      that: ansible_version.full is version_compare(win10cis_min_ansible_version, '>=')
      msg: You must use Ansible {{ win10cis_min_ansible_version }} or greater.
  tags:
      - always

- name: Include The Preliminary Tasks
  ansible.builtin.include_tasks:
      file: prelim.yml
  tags:
      - always
      - prelim_tasks

- name: Include Section 1 Patches
  ansible.builtin.import_tasks:
      file: section_1/main.yml
  when: win10cis_section1
  tags:
      - section1

- name: Include Section 2 Patches
  ansible.builtin.import_tasks:
      file: section_2/main.yml
  when: win10cis_section2
  tags:
      - section2

- name: Include Section 5 Patches
  ansible.builtin.import_tasks:
      file: section_5/main.yml
  when: win10cis_section5
  tags:
      - section5

- name: Include Section 9 Patches
  ansible.builtin.import_tasks:
      file: section_9/main.yml
  when: win10cis_section9
  tags:
      - section9

- name: Include Section 17 Patches
  ansible.builtin.import_tasks:
      file: section_17/main.yml
  when: win10cis_section17
  tags:
      - section17

- name: Include Section 18 Patches
  ansible.builtin.import_tasks:
      file: section_18/main.yml
  when: win10cis_section18
  tags:
      - section18

- name: Include Section 19 Patches
  ansible.builtin.import_tasks:
      file: section_19/main.yml
  when: win10cis_section19
  tags:
      - section19

- name: Run Post Tasks
  ansible.builtin.import_tasks: post.yml
  tags:
      - post_tasks
      - always

- name: If Warnings found Output count and control IDs affected
  ansible.builtin.debug:
      msg:
          - "You have {{ warn_count }} Warning(s) that require investigation(s). Their IDâ€™s are listed below:"
          - "{{ warn_control_list }}"
  when: warn_count != 0
  tags:
      - always
