---

- name: "18.6.9.1 | PATCH | Ensure Turn on Mapper IO LLTDIO driver is set to Disabled"
  block:
      - name: "18.6.9.1 | PATCH | Ensure Turn on Mapper IO LLTDIO driver is set to Disabled | AllowLLTDIOOndomain"
        ansible.windows.win_regedit:
            path: HKLM:\Software\Policies\Microsoft\Windows\Lltd
            name: AllowLLTDIOOndomain
            data: 0
            type: dword

      - name: "18.6.9.1 | PATCH | Ensure Turn on Mapper IO LLTDIO driver is set to Disabled | AllowLLTDIOOnPublicNet"
        ansible.windows.win_regedit:
            path: HKLM:\Software\Policies\Microsoft\Windows\Lltd
            name: AllowLLTDIOOnPublicNet
            data: 0
            type: dword

      - name: "18.6.9.1 | PATCH | Ensure Turn on Mapper IO LLTDIO driver is set to Disabled | EnableLLTDIO"
        ansible.windows.win_regedit:
            path: HKLM:\Software\Policies\Microsoft\Windows\Lltd
            name: EnableLLTDIO
            data: 0
            type: dword

      - name: "18.6.9.1 | PATCH | Ensure Turn on Mapper IO LLTDIO driver is set to Disabled | ProhibitLLTDIOOnPrivateNet"
        ansible.windows.win_regedit:
            path: HKLM:\Software\Policies\Microsoft\Windows\Lltd
            name: ProhibitLLTDIOOnPrivateNet
            data: 0
            type: dword
  when: win10cis_rule_18_6_9_1
  tags:
      - level2-high-security-sensitive-data-environment
      - patch
      - automated
      - rule_18.6.9.1
      - mapper

- name: "18.6.9.2 | PATCH | Ensure Turn on Responder RSPNDR driver is set to Disabled"
  block:
      - name: "18.6.9.2 | PATCH | Ensure Turn on Responder RSPNDR driver is set to Disabled | AllowRspndrOnDomain"
        ansible.windows.win_regedit:
            path: HKLM:\Software\Policies\Microsoft\Windows\Lltd
            name: AllowRspndrOnDomain
            data: 0
            type: dword

      - name: "18.6.9.2 | PATCH | Ensure Turn on Responder RSPNDR driver is set to Disabled | AllowRspndrOnPublicNet"
        ansible.windows.win_regedit:
            path: HKLM:\Software\Policies\Microsoft\Windows\Lltd
            name: AllowRspndrOnPublicNet
            data: 0
            type: dword

      - name: "18.6.9.2 | PATCH | Ensure Turn on Responder RSPNDR driver is set to Disabled | EnableRspndr"
        ansible.windows.win_regedit:
            path: HKLM:\Software\Policies\Microsoft\Windows\Lltd
            name: EnableRspndr
            data: 0
            type: dword

      - name: "18.6.9.2 | PATCH | Ensure Turn on Responder RSPNDR driver is set to Disabled | ProhibitRspndrOnPrivateNet"
        ansible.windows.win_regedit:
            path: HKLM:\Software\Policies\Microsoft\Windows\Lltd
            name: ProhibitRspndrOnPrivateNet
            data: 0
            type: dword
  when: win10cis_rule_18_6_9_2
  tags:
      - level2-high-security-sensitive-data-environment
      - patch
      - automated
      - rule_18.6.9.2
      - responder
