---

- name: "18.6.11.2 | PATCH | Ensure Prohibit installation and configuration of Network Bridge on your DNS domain network is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\Network Connections
      name: NC_AllowNetBridge_NLA
      data: 0
      type: dword
  when: win10cis_rule_18_6_11_2
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.6.11.2
      - network_bridge

- name: "18.6.11.3 | PATCH | Ensure Prohibit use of Internet Connection Sharing on your DNS domain network is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Network Connections
      name: NC_ShowSharedAccessUI
      data: 0
      type: dword
  when: win10cis_rule_18_6_11_3
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.6.11.3
      - ics

- name: "18.6.11.4 | PATCH | Ensure Require domain users to elevate when setting a networks location is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\Network Connections
      name: NC_StdDomainUserSetLocation
      data: 1
      type: dword
  when: win10cis_rule_18_6_11_4
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.6.11.4
      - domain_users
