---

- name: "18.6.21.1 | PATCH | Ensure Minimize the number of simultaneous connections to the Internet or a Windows Domain is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\Wcmsvc\Grouppolicy
      name: fMinimizeConnections
      data: 3
      type: dword
  when: win10cis_rule_18_6_21_1
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.6.21.1
      - domain

- name: "18.6.21.2 | PATCH | Ensure Prohibit connection to non-domain networks when connected to domain authenticated network is set to Enabled MS only"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\Wcmsvc\Grouppolicy
      name: fBlockNonDomain
      data: 1
      type: dword
  when:
      - win10cis_rule_18_6_21_2
      - discovered_domain_joined
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.6.21.2
      - non_domain
