---

- name: "18.6.19.2.1 | PATCH | Disable IPv6 Ensure TCPIP6 Parameter DisabledComponents is set to 0xff 255"
  ansible.windows.win_regedit:
      path: HKLM:\System\CurrentControlSet\Services\TCPIP6\Parameters
      name: DisabledComponents
      data: 255
      type: dword
  when: win10cis_rule_18_6_19_2_1
  tags:
      - level2-high-security-sensitive-data-environment
      - patch
      - automated
      - rule_18.6.19.2.1
      - parameters
      - ipv6
