---

- name: "18.6.5.1 | PATCH | Ensure Enable Font Providers is set to Disabled"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\System
      name: EnableFontProviders
      data: 0
      type: dword
  when: win10cis_rule_18_6_5_1
  tags:
      - level2-high-security-sensitive-data-environment
      - patch
      - automated
      - rule_18.6.5.1
      - font_providers
