---

- name: "18.6.20.1 | PATCH | Ensure Configuration of wireless settings using Windows Connect Now is set to Disabled"
  block:
      - name: "18.6.20.1 | PATCH | Ensure Configuration of wireless settings using Windows Connect Now is set to Disabled | EnableRegistrars"
        ansible.windows.win_regedit:
            path: HKLM:\Software\Policies\Microsoft\Windows\Wcn\Registrars
            name: EnableRegistrars
            data: 0
            type: dword

      - name: "18.6.20.1 | PATCH | Ensure Configuration of wireless settings using Windows Connect Now is set to Disabled | DisableUPnPRegistrar"
        ansible.windows.win_regedit:
            path: HKLM:\Software\Policies\Microsoft\Windows\Wcn\Registrars
            name: DisableUPnPRegistrar
            data: 0
            type: dword

      - name: "18.6.20.1 | PATCH | Ensure Configuration of wireless settings using Windows Connect Now is set to Disabled | DisableInBand802DOT11Registrar"
        ansible.windows.win_regedit:
            path: HKLM:\Software\Policies\Microsoft\Windows\Wcn\Registrars
            name: DisableInBand802DOT11Registrar
            data: 0
            type: dword

      - name: "18.6.20.1 | PATCH | Ensure Configuration of wireless settings using Windows Connect Now is set to Disabled | DisableFlashConfigRegistrar"
        ansible.windows.win_regedit:
            path: HKLM:\Software\Policies\Microsoft\Windows\Wcn\Registrars
            name: DisableFlashConfigRegistrar
            data: 0
            type: dword

      - name: "18.6.20.1 | PATCH | Ensure Configuration of wireless settings using Windows Connect Now is set to Disabled | DisableWPDRegistrar"
        ansible.windows.win_regedit:
            path: HKLM:\Software\Policies\Microsoft\Windows\Wcn\Registrars
            name: DisableWPDRegistrar
            data: 0
            type: dword
  when: win10cis_rule_18_6_20_1
  tags:
      - level2-high-security-sensitive-data-environment
      - patch
      - automated
      - rule_18.6.20.1
      - wireless

- name: "18.6.20.2 | PATCH | Ensure Prohibit access of the Windows Connect Now wizards is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\Wcn\Ui
      name: DisableWcnUi
      data: 1
      type: dword
  when: win10cis_rule_18_6_20_2
  tags:
      - level2-high-security-sensitive-data-environment
      - patch
      - automated
      - rule_18.6.20.2
      - windows_connect_now
