---

- name: "18.9.7.1.1 | PATCH | Ensure 'Prevent installation of devices that match any of these device IDs' is set to 'Enabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceInstall\Restrictions
      name: DenyDeviceIDs
      data: 1
      type: dword
  when: win10cis_rule_18_9_7_1_1
  tags:
      - level1-bitlocker
      - level2-bitlocker
      - bitlocker
      - level1-bitlocker-next-generation-windows-security
      - patch
      - automated
      - rule_18.9.7.1.1
      - device_installations_restrictions

- name: "18.9.7.1.2 | PATCH | Ensure 'Prevent installation of devices that match any of these device IDs: Prevent installation of devices that match any of these device IDs' is set to 'PCI\\CC_0C0A'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceInstall\Restrictions\DenyDeviceIDs
      name: 1
      data: PCI\CC_0C0A
      type: string
  when: win10cis_rule_18_9_7_1_2
  tags:
      - level1-bitlocker
      - level2-bitlocker
      - bitlocker
      - level1-bitlocker-next-generation-windows-security
      - patch
      - automated
      - rule_18.9.7.1.2
      - device_installations_restrictions

- name: "18.9.7.1.3 | PATCH | Ensure 'Prevent installation of devices that match any of these device IDs: Also apply to matching devices that are already installed.' is set to 'True'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceInstall\Restrictions
      name: DenyDeviceIDsRetroactive
      data: 1
      type: dword
  when: win10cis_rule_18_9_7_1_3
  tags:
      - level1-bitlocker
      - level2-bitlocker
      - bitlocker
      - level1-bitlocker-next-generation-windows-security
      - patch
      - automated
      - rule_18.9.7.1.3
      - device_installations_restrictions

- name: "18.9.7.1.4 | PATCH | Ensure 'Prevent installation of devices using drivers that match these device setup classes' is set to 'Enabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceInstall\Restrictions
      name: DenyDeviceClasses
      data: 1
      type: dword
  when: win10cis_rule_18_9_7_1_4
  tags:
      - level1-bitlocker
      - level2-bitlocker
      - bitlocker
      - level1-bitlocker-next-generation-windows-security
      - patch
      - automated
      - rule_18.9.7.1.4
      - device_installations_restrictions

- name: "18.9.7.1.5 | PATCH | Ensure 'Prevent installation of devices using drivers that match these device setup classes' is set to 'Enabled'"
  block:
      - name: "18.9.7.1.5 | PATCH | Ensure 'Prevent installation of devices using drivers that match these device setup classes' is set to 'Enabled' | IEEE 1394 devices that support the SBP2 Protocol Class."
        ansible.windows.win_regedit:
            path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceInstall\Restrictions\DenyDeviceClasses
            name: 1
            data: '{d48179be-ec20-11d1-b6b8-00c04fa372a7}'
            type: string

      - name: "18.9.7.1.5 | PATCH | Ensure 'Prevent installation of devices using drivers that match these device setup classes' is set to 'Enabled' | IEEE 1394 devices that support the IEC-61883 Protocol Class."
        ansible.windows.win_regedit:
            path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceInstall\Restrictions\DenyDeviceClasses
            name: 2
            data: '{7ebefbc0-3200-11d2-b4c2-00a0C9697d07}'
            type: string

      - name: "18.9.7.1.5 | PATCH | Ensure 'Prevent installation of devices using drivers that match these device setup classes' is set to 'Enabled' | IEEE 1394 devices that support the AVC Protocol Class."
        ansible.windows.win_regedit:
            path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceInstall\Restrictions\DenyDeviceClasses
            name: 3
            data: '{c06ff265-ae09-48f0-812c-16753d7cba83}'
            type: string

      - name: "18.9.7.1.5 | PATCH | Ensure 'Prevent installation of devices using drivers that match these device setup classes' is set to 'Enabled' | IEEE 1394 Host Bus Controller Class."
        ansible.windows.win_regedit:
            path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceInstall\Restrictions\DenyDeviceClasses
            name: 4
            data: '{6bdd1fc1-810f-11d0-bec7-08002be2092f}'
            type: string
  when: win10cis_rule_18_9_7_1_5
  tags:
      - level1-bitlocker
      - level2-bitlocker
      - bitlocker
      - level1-bitlocker-next-generation-windows-security
      - patch
      - automated
      - rule_18.9.7.1.5
      - device_installations_restrictions

- name: "18.9.7.1.6 | PATCH | Ensure 'Prevent installation of devices using drivers that match these device setup classes: Also apply to matching devices that are already installed.' is set to 'True'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceInstall\Restrictions
      name: DenyDeviceClassesRetroactive
      data: 1
      type: dword
  when: win10cis_rule_18_9_7_1_6
  tags:
      - level1-bitlocker
      - level2-bitlocker
      - bitlocker
      - level1-bitlocker-next-generation-windows-security
      - patch
      - automated
      - rule_18.9.7.1.6
      - device_installations_restrictions

- name: "18.9.7.2 | PATCH | Ensure Prevent device metadata retrieval from the Internet is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Device Metadata
      name: PreventDeviceMetadataFromNetwork
      data: 1
      type: dword
  when: win10cis_rule_18_9_7_2
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.9.7.2
      - metadata
