---

- name: "18.9.3.1 | PATCH | Ensure Include command line in process creation events is set to Enabled."
  ansible.windows.win_regedit:
      path: HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System\Audit
      name: ProcessCreationIncludeCmdLine_Enabled
      data: 1
      type: dword
  when: win10cis_rule_18_9_3_1
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.9.3.1
