---

- name: "19.1.3.1 | PATCH | Ensure Enable screen saver is set to Enabled"
  ansible.windows.win_regedit:
      path: HKU:\{{ item }}\Software\Policies\Microsoft\Windows\Control Panel\Desktop
      name: ScreenSaveActive
      data: 1
      type: string
  loop: "{{ hku_loaded_list }}"
  notify: change_requires_reboot
  when:
      - win10cis_rule_19_1_3_1
  tags:
      - level1-corporate-enterprise-environment
      - rule_19.1.3.1
      - automated
      - patch
      - screen-saver

- name: "19.1.3.2 | PATCH | Ensure Password protect the screen saver is set to Enabled"
  ansible.windows.win_regedit:
      path: HKU:\{{ item }}\Software\Policies\Microsoft\Windows\Control Panel\Desktop
      name: ScreenSaverIsSecure
      data: 1
      type: string
  loop: "{{ hku_loaded_list }}"
  notify: change_requires_reboot
  when:
      - win10cis_rule_19_1_3_2
  tags:
      - level1-corporate-enterprise-environment
      - rule_19.1.3.2
      - automated
      - patch
      - password-protect-screen-saver

- name: "19.1.3.3 | PATCH | Ensure Screen saver timeout is set to Enabled 900 seconds or fewer but not 0"
  block:
      - name: Warning Check For Variable Standards."
        ansible.builtin.debug:
            msg:
                - "Warning!! You have a invalid time set for win10cis_screen_saver_timeout please read"
                - "the notes for the variable and make the necessary change to the variable to be in compliance."
        when:
            - win10cis_screen_saver_timeout == 0 or
              win10cis_screen_saver_timeout > 900

      - name: Set warning count."
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        vars:
            warn_control_id: '19.1.3.3'
        when:
            - win10cis_screen_saver_timeout == 0 or
              win10cis_screen_saver_timeout > 900

      - name: "19.1.3.3 | PATCH | Ensure Screen saver timeout is set to Enabled 900 seconds or fewer but not 0"
        ansible.windows.win_regedit:
            path: HKU:\{{ item }}\Software\Policies\Microsoft\Windows\Control Panel\Desktop
            name: ScreenSaveTimeOut
            data: "{{ win10cis_screen_saver_timeout }}"
            type: string
        loop: "{{ hku_loaded_list }}"
        when:
            - win10cis_screen_saver_timeout > 0
            - win10cis_screen_saver_timeout <= 900
  notify: change_requires_reboot
  when:
      - win10cis_rule_19_1_3_3
  tags:
      - level1-corporate-enterprise-environment
      - rule_19.1.3.3
      - automated
      - patch
      - screen-saver-timeout
