---

- name: "18.10.40.1 | PATCH | Ensure Allow Message Service Cloud Sync is set to Disabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\Messaging
      name: AllowMessageSync
      data: 0
      type: dword
  when: win10cis_rule_18_10_40_1
  tags:
      - level2-high-security-sensitive-data-environment
      - patch
      - automated
      - rule_18.10.40.1
      - cloud_sync
