---

- name: "18.10.65.1 | PATCH | Ensure 'Disable all apps from Microsoft Store' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\WindowsStore
      name: DisableStoreApps
      data: 1
      type: dword
  when: win10cis_rule_18_10_65_1
  tags:
      - level2-high-security-sensitive-data-environment
      - patch
      - automated
      - rule_18.10.65.1

- name: "18.10.65.2 | PATCH | Ensure 'Only display the private store within the Microsoft Store' is set to 'Enabled'"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\WindowsStore
      name: RequirePrivateStoreOnly
      data: 1
      type: dword
  when: win10cis_rule_18_10_65_2
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.10.65.2

- name: "18.10.65.3 | PATCH | Ensure 'Turn off Automatic Download and Install of updates' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\WindowsStore
      name: AutoDownload
      data: 4
      type: dword
  when: win10cis_rule_18_10_65_3
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.10.65.3

- name: "18.10.65.4 | PATCH | Ensure 'Turn off the offer to update to the latest version of Windows' is set to 'Enabled'"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\WindowsStore
      name: DisableOSUpgrade
      data: 1
      type: dword
  when: win10cis_rule_18_10_65_4
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.10.65.4

- name: "18.10.65.5 | PATCH | Ensure 'Turn off the Store application' is set to 'Enabled'"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\WindowsStore
      name: RemoveWindowsStore
      data: 1
      type: dword
  when: win10cis_rule_18_10_65_5
  tags:
      - level2-high-security-sensitive-data-environment
      - patch
      - automated
      - rule_18.10.65.5
