---

- name: "18.10.89.1.1 | PATCH | Ensure Allow Basic authentication is set to Disabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\Winrm\Client
      name: AllowBasic
      data: 0
      type: dword
  when:
      - win10cis_rule_18_10_89_1_1
      - not win_skip_for_test
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.10.89.1.1
      - automated
      - patch
      - winrm-client

- name: "18.10.89.1.2 | PATCH | Ensure Allow unencrypted traffic is set to Disabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\Winrm\Client
      name: AllowUnencryptedTraffic
      data: 0
      type: dword
  when:
      - win10cis_rule_18_10_89_1_2
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.10.89.1.2
      - automated
      - patch
      - winrm-client

- name: "18.10.89.1.3 | PATCH | Ensure Disallow Digest authentication is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\Winrm\Client
      name: AllowDigest
      data: 0
      type: dword
  when:
      - win10cis_rule_18_10_89_1_3
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.10.89.1.3
      - automated
      - patch
      - winrm-client

- name: "18.10.89.2.1 | PATCH | Ensure Allow Basic authentication is set to Disabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\Winrm\Service
      name: AllowBasic
      data: 0
      type: dword
  when:
      - win10cis_rule_18_10_89_2_1
      - not win_skip_for_test
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.10.89.2.1
      - automated
      - patch
      - winrm-service

# This control will have to be set to Enabled (1) to allow for continued remote management via Ansible following machine restart
- name: "18.10.89.2.2 | PATCH | Ensure Allow remote server management through WinRM is set to Disabled"
  block:
      - name: "18.10.89.2.2 | AUDIT | Ensure Allow remote server management through WinRM is set to Disabled | Warning Check For Variable Standards."
        ansible.builtin.debug:
            msg:
                - "Warning!! You have an invalid setting for win10cis_winrm_allow_auto_config. Please read"
                - "the notes for the variable and make the necessary change to the variable to be in compliance."
        when:
            - win10cis_winrm_allow_auto_config != 0
            - win10cis_winrm_allow_auto_config != 1

      - name: "18.10.89.2.2 | AUDIT | Ensure Allow remote server management through WinRM is set to Disabled | Warn Count."
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        vars:
            warn_control_id: '18.10.89.2.2'
        when:
            - win10cis_winrm_allow_auto_config != 0
            - win10cis_winrm_allow_auto_config != 1

      - name: "18.10.89.2.2 | PATCH | Ensure Allow remote server management through WinRM is set to Disabled | Set Variable."
        ansible.windows.win_regedit:
            path: HKLM:\Software\Policies\Microsoft\Windows\Winrm\Service
            name: AllowAutoConfig
            data: "{{ win10cis_winrm_allow_auto_config }}"
            type: dword
        when:
            - win10cis_winrm_allow_auto_config == 0 or win10cis_winrm_allow_auto_config == 1
  when:
      - win10cis_rule_18_10_89_2_2
      - not win_skip_for_test
  tags:
      - level2-high-security-sensitive-data-environment
      - rule_18.10.89.2.2
      - automated
      - patch
      - winrm-service

- name: "18.10.89.2.3 | PATCH | Ensure Allow unencrypted traffic is set to Disabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\Winrm\Service
      name: AllowUnencryptedTraffic
      data: 0
      type: dword
  when:
      - win10cis_rule_18_10_89_2_3
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.10.89.2.3
      - automated
      - patch
      - winrm-service

- name: "18.9.102.2.4 | PATCH | Ensure Disallow WinRM from storing RunAs credentials is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\Winrm\Service
      name: DisableRunAs
      data: 1
      type: dword
  when:
      - win10cis_rule_18_10_89_2_4
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.10.89.2.4
      - automated
      - patch
      - winrm-service
