---

- name: "18.10.13.1 | PATCH | Ensure Require pin for pairing is set to Enabled First Time OR Enabled Always"
  block:
      - name: "18.10.13.1 | PATCH | Ensure Require pin for pairing is set to Enabled First Time OR Enabled Always | Set Variable."
        ansible.windows.win_regedit:
            path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Connect
            name: RequirePinForPairing
            data: "{{ win10cis_require_pin_for_pairing }}"
            type: dword
        when: win10cis_require_pin_for_pairing == 1 or win10cis_require_pin_for_pairing == 2

      - name: "18.10.13.1 | AUDIT | Ensure Require pin for pairing is set to Enabled First Time OR Enabled Always | Warning Check For Variable Standards."
        ansible.builtin.debug:
            msg:
                - "Warning!! You have an invalid setting for win10cis_require_pin_for_pairing. Please read"
                - "the notes for the variable and make the necessary change to the variable to be in compliance."
        when:
            - win10cis_require_pin_for_pairing != 1
            - win10cis_require_pin_for_pairing != 2

      - name: "18.10.13.1 | AUDIT | Ensure Require pin for pairing is set to Enabled First Time OR Enabled Always | Warn Count."
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        vars:
            warn_control_id: '18.10.13.1'
        when:
            - win10cis_require_pin_for_pairing != 1
            - win10cis_require_pin_for_pairing != 2
  when: win10cis_rule_18_10_13_1
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.10.13.1
      - pin
