---

- name: "18.10.4.1 | PATCH | Ensure 'Let Windows apps activate with voice while the system is locked' is set to 'Enabled: Force Deny'"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\AppPrivacy
      name: LetAppsActivateWithVoiceAboveLock
      data: 1
      type: dword
  when: win10cis_rule_18_10_4_1
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.10.4.1
      - voice
