---

- name: "18.10.10.1 | PATCH | Ensure 'Allow Use of Camera' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Camera
      name: AllowCamera
      data: 0
      type: dword
  when: win10cis_rule_18_10_10_1
  tags:
      - level2-high-security-sensitive-data-environment
      - patch
      - automated
      - rule_18.10.10.1
      - camera
