---

- name: "2.3.9.1 | PATCH | Ensure Microsoft network server Amount of idle time required before suspending session is set to 15 or fewer minutes"
  block:
      - name: "2.3.9.1 | PATCH | Ensure Microsoft network server Amount of idle time required before suspending session is set to 15 or fewer minutes. | Apply Settings To Registry."
        ansible.windows.win_regedit:
            path: HKLM:\System\Currentcontrolset\Services\Lanmanserver\Parameters
            name: AutoDisconnect
            data: "{{ win10cis_smb_auto_disconnect_time }}"
            type: dword
        when: win10cis_smb_auto_disconnect_time <= 15

      - name: "2.3.9.1 | AUDIT | Ensure Microsoft network server Amount of idle time required before suspending session is set to 15 or fewer minutes. | Warning Check For Variable Standards."
        ansible.builtin.debug:
            msg:
                - "Warning!! You have an invalid number of minutes set for win10cis_smb_auto_disconnect_time. Please read"
                - "the notes for the variable and make the necessary change to the variable to be in compliance."
        when: win10cis_smb_auto_disconnect_time > 15

      - name: "2.3.9.1 | AUDIT | Ensure Microsoft network server Amount of idle time required before suspending session is set to 15 or fewer minutes. | Warn Count."
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        vars:
            warn_control_id: '2.3.7.7'
        when: win10cis_smb_auto_disconnect_time > 15
  when:
      - win10cis_rule_2_3_9_1
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_2.3.9.1

- name: "2.3.9.2 | PATCH | Ensure Microsoft network server Digitally sign communications always is set to Enabled."
  ansible.windows.win_regedit:
      path: HKLM:\System\Currentcontrolset\Services\Lanmanserver\Parameters
      name: RequireSecuritySignature
      data: 1
      type: dword
  when:
      - win10cis_rule_2_3_9_2
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_2.3.9.2

- name: "2.3.9.3 | PATCH | Ensure Microsoft network server Digitally sign communications if client agrees is set to Enabled."
  ansible.windows.win_regedit:
      path: HKLM:\System\Currentcontrolset\Services\Lanmanserver\Parameters
      name: EnableSecuritySignature
      data: 1
      type: dword
  when:
      - win10cis_rule_2_3_9_3
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_2.3.9.3

- name: "2.3.9.4 | PATCH | Ensure Microsoft network server Disconnect clients when logon hours expire is set to Enabled."
  ansible.windows.win_regedit:
      path: HKLM:\System\Currentcontrolset\Services\Lanmanserver\Parameters
      name: EnableForcedLogoff
      data: 1
      type: dword
  when: win10cis_rule_2_3_9_4
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_2.3.9.4

- name: "2.3.9.5 | PATCH | Ensure Microsoft network server Server SPN target name validation level is set to Accept if provided by client or higher."
  block:
      - name: "2.3.9.5 | PATCH | Ensure Microsoft network server Server SPN target name validation level is set to Accept if provided by client or higher. | Apply Registry Setting."
        ansible.windows.win_regedit:
            path: HKLM:\System\Currentcontrolset\Services\Lanmanserver\Parameters
            name: SMBServerNameHardeningLevel
            data: "{{ win10cis_smb_server_name_hardening_level }}"
            type: dword
        when: win10cis_smb_server_name_hardening_level == 1 or win10cis_smb_server_name_hardening_level == 2

      - name: "2.3.9.5 | AUDIT | Ensure Microsoft network server Server SPN target name validation level is set to Accept if provided by client or higher. | Warning Check For Variable Standards."
        ansible.builtin.debug:
            msg:
                - "Warning!! You have an invalid number variable set for win10cis_smb_server_name_hardening_level. Please read"
                - "the notes for the variable and make the necessary change to the variable to be in compliance."
        when: win10cis_smb_server_name_hardening_level == 0 or win10cis_smb_server_name_hardening_level > 2

      - name: "2.3.9.5 | AUDIT | Ensure Microsoft network server Server SPN target name validation level is set to Accept if provided by client or higher. | Warn Count."
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        vars:
            warn_control_id: '2.3.9.5'
        when: win10cis_smb_server_name_hardening_level == 0 or win10cis_smb_server_name_hardening_level > 2
  when: win10cis_rule_2_3_9_5
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_2.3.9.5
