---

- name: "2.3.2.1 | PATCH | Ensure Audit Force audit policy subcategory settings Windows Vista or later to override audit policy category settings is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\System\CurrentControlSet\Control\Lsa
      name: SCENoApplyLegacyAuditPolicy
      data: 1
      type: dword
  when: win10cis_rule_2_3_2_1
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_2.3.2.1

- name: "2.3.2.2 | PATCH | Ensure Audit Shut down system immediately if unable to log security audits is set to Disabled"
  ansible.windows.win_regedit:
      path: HKLM:\System\CurrentControlSet\Control\Lsa
      name: CrashOnAuditFail
      data: 0
      type: dword
  when: win10cis_rule_2_3_2_2
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_2.3.2.2
