---

- name: "2.3.17.1 | PATCH | Ensure User Account Control Admin Approval Mode for the Built-in Administrator account is set to Enabled."
  ansible.windows.win_regedit:
      path: HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System
      name: FilterAdministratorToken
      data: 1
      type: dword
  when:
      - win10cis_rule_2_3_17_1
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_2.3.17.1

- name: "2.3.17.2 | PATCH | Ensure 'User Account Control: Behavior of the elevation prompt for administrators in Admin Approval Mode' is set to 'Prompt for consent on the secure desktop' or higher."
  ansible.windows.win_regedit:
      path: HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System
      name: ConsentPromptBehaviorAdmin
      data: "{{ win10cis_consent_prompt_behavior_admin }}"
      type: dword
  when:
      - win10cis_rule_2_3_17_2
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_2.3.17.2

- name: "2.3.17.3 | PATCH | Ensure User Account Control Behavior of the elevation prompt for standard users is set to Automatically deny elevation requests."
  ansible.windows.win_regedit:
      path: HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System
      name: ConsentPromptBehaviorUser
      data: 0
      type: dword
  when:
      - win10cis_rule_2_3_17_3
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_2.3.17.3

- name: "2.3.17.4 | PATCH | Ensure User Account Control Detect application installations and prompt for elevation is set to Enabled."
  ansible.windows.win_regedit:
      path: HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System
      name: EnableInstallerDetection
      data: 1
      type: dword
  when:
      - win10cis_rule_2_3_17_4
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_2.3.17.4

- name: "2.3.17.5 | PATCH | Ensure User Account Control Only elevate UIAccess applications that are installed in secure locations is set to Enabled."
  ansible.windows.win_regedit:
      path: HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System
      name: EnableSecureUIAPaths
      data: 1
      type: dword
  when:
      - win10cis_rule_2_3_17_5
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_2.3.17.5

- name: "2.3.17.6 | PATCH | Ensure User Account Control Run all administrators in Admin Approval Mode is set to Enabled."
  ansible.windows.win_regedit:
      path: HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System
      name: EnableLUA
      data: 1
      type: dword
  when:
      - win10cis_rule_2_3_17_6
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_2.3.17.6

- name: "2.3.17.7 | PATCH | Ensure User Account Control Switch to the secure desktop when prompting for elevation is set to Enabled."
  ansible.windows.win_regedit:
      path: HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System
      name: PromptOnSecureDesktop
      data: 1
      type: dword
  when: win10cis_rule_2_3_17_7
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_2.3.17.7

- name: "2.3.17.8 | PATCH | Ensure User Account Control Virtualize file and registry write failures to per-user locations is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System
      name: EnableVirtualization
      data: 1
      type: dword
  when: win10cis_rule_2_3_17_8
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_2.3.17.8
