---

- name: "1.1.1 | PATCH | Ensure Enforce password history is set to 24 or more passwords."
  block:
      - name: "1.1.1 | PATCH | Ensure Enforce password history is set to 24 or more passwords. | Set Variable."
        community.windows.win_security_policy:
            section: System Access
            key: PasswordHistorySize
            value: "{{ win10cis_max_passwords_saved }}"
        when: win10cis_max_passwords_saved == 24

      - name: "1.1.1 | AUDIT | Ensure Enforce password history is set to 24 or more passwords. | Check for more then 24 saved passwords warning."
        ansible.builtin.debug:
            msg:
                - "Warning!! You have an invalid number of maximum passwords set in win10cis_max_passwords_saved, please read"
                - "the notes for the variable and make the necessary change to the variable to be in compliance."
        when: win10cis_max_passwords_saved > 24 or win10cis_max_passwords_saved <= 23

      - name: "1.1.1 | AUDIT | Ensure Enforce password history is set to 24 or more passwords. | Set warning count"
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        vars:
            warn_control_id: '1.1.1'
        when: win10cis_max_passwords_saved > 24 or win10cis_max_passwords_saved <= 23
  when: win10cis_rule_1_1_1
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_1.1.1

- name: "1.1.2 | PATCH | Ensure Maximum password age is set to 365 or fewer days but not 0."
  block:
      - name: "1.1.2 | PATCH | Ensure Maximum password age is set to 365 or fewer days but not 0. | Set Variable."
        community.windows.win_security_policy:
            section: System Access
            key: MaximumPasswordAge
            value: "{{ win10cis_maximum_password_age }}"
        when:
            - win10cis_maximum_password_age <= 365
            - win10cis_maximum_password_age > 0

      - name: "1.1.2 | AUDIT | Ensure Maximum password age is set to 365 or fewer days but not 0. | Warning check for maximum password age time."
        ansible.builtin.debug:
            msg:
                - "Warning!! You have an invalid age set for win10cis_maximum_password_age, please read"
                - "the notes for the variable and make the necessary change to the variable to be in compliance."
        when: win10cis_maximum_password_age > 365 or win10cis_maximum_password_age == 0

      - name: "1.1.2 | AUDIT | Ensure Maximum password age is set to 365 or fewer days but not 0. | Set warning count."
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        vars:
            warn_control_id: '1.1.2'
        when: win10cis_maximum_password_age > 365 or win10cis_maximum_password_age == 0
  when: win10cis_rule_1_1_2
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_1.1.2

- name: "1.1.3 | PATCH | Ensure Minimum password age is set to 1 or more days."
  block:
      - name: "1.1.3 | PATCH | Ensure Minimum password age is set to 1 or more days. | Set Variable."
        community.windows.win_security_policy:
            section: System Access
            key: MinimumPasswordAge
            value: "{{ win10cis_minimum_password_age }}"
        when: win10cis_minimum_password_age <= 999 or win10cis_minimum_password_age > 0

      - name: "1.1.3 | AUDIT | Ensure Minimum password age is set to 1 or more days. | Warning check for minimim password age."
        ansible.builtin.debug:
            msg:
                - "Warning!! You have an invalid age set for win10cis_minimum_password_age, please read"
                - "the notes for the variable and make the necessary change to the variable to be in compliance."
        when: win10cis_minimum_password_age > 999 or win10cis_minimum_password_age == 0

      - name: "1.1.3 | AUDIT | Ensure Minimum password age is set to 1 or more days. | Set warning count."
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        vars:
            warn_control_id: '1.1.3'
        when: win10cis_minimum_password_age > 999 or win10cis_minimum_password_age == 0
  when: win10cis_rule_1_1_3
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_1.1.3

- name: "1.1.4 | PATCH | Ensure Minimum password length is set to 14 or more characters."
  block:
      - name: "1.1.4 | PATCH | Ensure Minimum password length is set to 14 or more characters. | Set Variable."
        community.windows.win_security_policy:
            section: System Access
            key: MinimumPasswordLength
            value: "{{ win10cis_minimum_password_length }}"
        when: win10cis_minimum_password_length >= 14

      - name: "1.1.4 | AUDIT | Ensure Minimum password length is set to 14 or more characters | Warning Check For Variable Standards."
        ansible.builtin.debug:
            msg:
                - "Warning!! You have an invalid length set for win10cis_minimum_password_length, please read"
                - "the notes for the variable and make the necessary change to the variable to be in compliance."
        when: win10cis_minimum_password_length < 14

      - name: "1.1.4 | AUDIT | Ensure Minimum password length is set to 14 or more characters. | Set warning count."
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        vars:
            warn_control_id: '1.1.4'
        when: win10cis_minimum_password_length < 14
  when: win10cis_rule_1_1_4
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_1.1.4

- name: "1.1.5 | PATCH | Ensure Password must meet complexity requirements is set to Enabled."
  community.windows.win_security_policy:
      section: System Access
      key: PasswordComplexity
      value: 1
  when: win10cis_rule_1_1_5
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_1.1.5

- name: "1.1.6 | PATCH | Ensure Relax minimum password length limits is set to Enabled."
  ansible.windows.win_regedit:
      path: HKLM:\System\CurrentControlSet\Control\SAM
      name: RelaxMinimumPasswordLengthLimits
      data: 1
      type: dword
  when: win10cis_rule_1_1_6
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_1.1.6

- name: "1.1.7 | PATCH | Ensure Store passwords using reversible encryption is set to Disabled"
  community.windows.win_security_policy:
      section: System Access
      key: ClearTextPassword
      value: 0
  when: win10cis_rule_1_1_7
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_1.1.7
