---

# We have found the order of tasks varies between cloud based instances and VM based instances.
# The task below loads the control group in the correct order for cloud based systems
- name:
      â€œ1.2.2 | PATCH | Ensure Account lockout threshold is set to 5 or fewer invalid logon attempt(s), but not 0.
       1.2.1 | PATCH | Ensure Account lockout duration is set to 15 or more minutes
       1.2.4 | PATCH | Ensure Reset account lockout counter after is set to 15 or more minutes."
  ansible.builtin.import_tasks:
      file: cis_1.2_cloud_lockout_order.yml
  when: discovered_cloud_based_system
  tags:
      - section01_cloud_lockout_order

# THE FOLLOWING 3 CONTROLS WILL FAIL UNLESS THEY ARE IN THE FOLLOWING ORDER FOR LOCAL BASED SYSTEMS.
# We have a seperate set of controls to run when the instance is running in a cloud environment, so that it does not fail.
# CONTROL 1.2.2, CONTROL 1.2.4, CONTROL 1.2.1
- name: "1.2.2 | PATCH | Ensure Account lockout threshold is set to 5 or fewer invalid logon attempt(s), but not 0."
  block:
      - name: "1.2.2 | PATCH | Ensure Account lockout threshold is set to 5 or fewer invalid logon attempt(s), but not 0. | Set Variable."
        community.windows.win_security_policy:
            section: System Access
            key: LockoutBadCount
            value: "{{ win10cis_bad_login_lockout_count }}"
        when:
            - win10cis_bad_login_lockout_count <= 5
            - win10cis_bad_login_lockout_count > 0

      - name: "1.2.2 | AUDIT | Ensure Account lockout threshold is set to 5 or fewer invalid logon attempt(s), but not 0. | Verify Variable Not 0 or more then 5 warning."
        ansible.builtin.debug:
            msg:
                - "Warning!! You have an invalid number of attempts set for win10cis_bad_login_lockout_count. Please read"
                - "the notes for the variable and make the necessary change to the variable to be in compliance."
        when: win10cis_bad_login_lockout_count > 5 or win10cis_bad_login_lockout_count == 0

      - name: "1.2.2 | AUDIT | Ensure Account lockout threshold is set to 5 or fewer invalid logon attempt(s), but not 0. | Set warning count."
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        vars:
            warn_control_id: '1.2.2'
        when: win10cis_bad_login_lockout_count > 5 or win10cis_bad_login_lockout_count == 0
  when:
      - win10cis_rule_1_2_2
      - not discovered_cloud_based_system
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_1.2.2
      - lockoutbadcount

- name: "1.2.4 | PATCH | Ensure Reset account lockout counter after is set to 15 or more minutes."
  block:
      - name: "1.2.4 | PATCH | Ensure Reset account lockout counter after is set to 15 or more minutes. | Set Variable."
        community.windows.win_security_policy:
            section: System Access
            key: ResetLockoutCount
            value: "{{ win10cis_account_lockout_counter_reset }}"
        when:
            - win10cis_account_lockout_counter_reset >= 15
            - win10cis_account_lockout_counter_reset <= win10cis_account_lockout_duration

      - name: "1.2.4 | PATCH | Ensure Reset account lockout counter after is set to 15 or more minutes. | Verify variable set to 15 or more minutes warning."
        ansible.builtin.debug:
            msg:
                - "Warning!! You have an invalid number of minutes set for win10cis_account_lockout_counter_reset. Please read"
                - "the notes for the variable and make the necessary change to the variable to be in compliance."
        when: win10cis_account_lockout_counter_reset > win10cis_account_lockout_duration or win10cis_account_lockout_counter_reset < 15

      - name: "1.2.4 | PATCH | Ensure Reset account lockout counter after is set to 15 or more minutes. | Set warning count."
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        vars:
            warn_control_id: '1.2.4'
        when: win10cis_account_lockout_counter_reset > win10cis_account_lockout_duration or win10cis_account_lockout_counter_reset < 15
  when:
      - win10cis_rule_1_2_4
      - not discovered_cloud_based_system
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_1.2.4
      - resetlockoutcount

# Speelman | added because of this error "Failed to import secedit.ini file from C:\\Users\\vagrant\\AppData\\Local\\Temp\\tmp81F3.tmp
- name: "1.2.1 | PATCH | Ensure Account lockout duration is set to 15 or more minutes."
  block:
      - name: "1.2.1 | PATCH | Ensure Account lockout duration is set to 15 or more minutes. | Set Variable"
        community.windows.win_security_policy:
            section: System Access
            key: LockoutDuration
            value: "{{ win10cis_account_lockout_duration }}"
        when: win10cis_account_lockout_duration >= 15

      - name: "1.2.1 | AUDIT | Ensure Account lockout duration is set to 15 or more minutes. | Verify variable set to 15 or more minutes warning."
        ansible.builtin.debug:
            msg:
                - "Warning!! You have an invalid number of minutes set for win10cis_account_lockout_duration please read"
                - "the notes for the variable and make the necessary change to the variable to be in compliance."
        when: win10cis_account_lockout_duration < 15

      - name: "1.2.1 | AUDIT | Ensure Account lockout duration is set to 15 or more minutes. | Set warning count."
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        vars:
            warn_control_id: '1.2.1'
        when: win10cis_account_lockout_duration < 15
  when:
      - win10cis_rule_1_2_1
      - not discovered_cloud_based_system
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_1.2.1
      - lockoutduration

- name: "1.2.3 | PATCH | Ensure Allow Administrator account lockout is set to Enabled."
  community.windows.win_security_policy:
      section: System Access
      key: AllowAdministratorLockout
      value: 1
  when: win10cis_rule_1_2_3
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_1.2.3
      - administrator
