---

- name: "9.1.1 | PATCH | Ensure 'Windows Firewall: Domain: Firewall state' is set to 'On (recommended)'"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windowsfirewall\Domainprofile
      name: EnableFirewall
      data: 1
      type: dword
  when: win10cis_rule_9_1_1
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_9.1.1
      - firewall_state

- name: "9.1.2 | PATCH | Ensure 'Windows Firewall: Domain: Inbound connections' is set to 'Block (default)'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\DomainProfile
      name: DefaultInboundAction
      data: 1
      type: dword
  when: win10cis_rule_9_1_2
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_9.1.2
      - inbound_connections

- name: "9.1.3 | PATCH | Ensure 'Windows Firewall: Domain: Settings: Display a notification' is set to 'No'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\DomainProfile
      name: DisableNotifications
      data: 1
      type: dword
  when: win10cis_rule_9_1_3
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_9.1.3
      - notifications

# title has slashes switched
- name: "9.1.4 | PATCH | Ensure 'Windows Firewall: Domain: Logging: Name' is set to '%SystemRoot%/System32/logfiles/firewall/domainfw.log'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\DomainProfile\Logging
      name: LogFilePath
      data: '{{ win10cis_domain_firewall_log_path }}'
      type: string
  when: win10cis_rule_9_1_4
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_9.1.4
      - logging_name

- name: "9.1.5 | PATCH | Ensure 'Windows Firewall: Domain: Logging: Size limit (KB)' is set to '16,384 KB or greater'"
  block:
      - name: "9.1.5 | PATCH | Ensure 'Windows Firewall: Domain: Logging: Size limit (KB)' is set to '16,384 KB or greater' | Apply Settings To Registry."
        ansible.windows.win_regedit:
            path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\DomainProfile\Logging
            name: LogFileSize
            data: '{{ win10cis_domain_firewall_log_size }}'
            type: dword
        when: win10cis_domain_firewall_log_size >= 16384

      - name: "9.1.5 | AUDIT | Ensure 'Windows Firewall: Domain: Logging: Size limit (KB)' is set to '16,384 KB or greater'. | Warning Check For Variable Standards."
        ansible.builtin.debug:
            msg:
                - "Warning!! You have an invalid size set for win10cis_domain_firewall_log_size. Please read"
                - "the notes for the variable and make the necessary change to the variable to be in compliance."
        when: win10cis_domain_firewall_log_size < 16384

      - name: "9.1.5 | AUDIT | Ensure 'Windows Firewall: Domain: Logging: Size limit (KB)' is set to '16,384 KB or greater' | Warn Count."
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        vars:
            warn_control_id: '9.1.5'
        when: win10cis_domain_firewall_log_size < 16384
  when: win10cis_rule_9_1_5
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_9.1.5
      - logging_size

- name: "9.1.6 | PATCH | Ensure 'Windows Firewall: Domain: Logging: Log dropped packets' is set to 'Yes'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\DomainProfile\Logging
      name: LogDroppedPackets
      data: 1
      type: dword
  when: win10cis_rule_9_1_6
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_9.1.6
      - logging_packets

- name: "9.1.7 | PATCH | Ensure 'Windows Firewall: Domain: Logging: Log successful connections' is set to 'Yes'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\DomainProfile\Logging
      name: LogSuccessfulConnections
      data: 1
      type: dword
  when: win10cis_rule_9_1_7
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_9.1.7
      - logging_connections
